### ISSUE TITLE
uninitialized constant Jekyll::Cache

### ISSUE THREAD

**Issue by hanniabu** [gouravkhunger/jekyll-url-metadata#4]
```
jekyll 3.9.0 | Error:  uninitialized constant Jekyll::Cache
```
```
{% assign meta = "https://wikipedia.org" | metadata %}
{{ meta }}
```
I received this error after following your install instructions and using your provided example and also included the "open-uri" and "nokogiri" gems. What I tried so far:

`bundle install`, `bundle update`, `gem cleanup`

Any ideas on what could be the issue?

**Comment by gouravkhunger** [comment]
Hi @hanniabu Could you please share your `Gemfile`, `_config.yml`, and the file where you have this:

```
{% assign meta = "https://wikipedia.org" | metadata %}
{{ meta }}
```

If those files are correct then my guess is there is something conflicting with the plugin and Jekyll version `3.9.0`. I will try to reproduce the error once you share your setup. Thanks for reporting!

**Comment by 10cheon00** [comment]
"jekyll" 3.9.3
"ruby" 3.2.1
"bundle" 2.4.6
I got this error too.
```
/home/ubuntu/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/jekyll-url-metadata-1.0.3/lib/jekyll-url-metadata/main.rb:17:in `cache': uninitialized constant Jekyll::Cache (NameError)

      @@cache ||= Jekyll::Cache.new("Jekyll::URLMetadata")
                        ^^^^^^^
        from /home/ubuntu/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/jekyll-url-metadata-1.0.3/lib/jekyll-url-metadata/main.rb:24:in `metadata'
```

**Comment by gouravkhunger** [comment]
Hi @10cheon00, Got it!

`Jekyll::Cache` was introduced in `v4.0.0`: [Release notes](https://jekyllrb.com/docs/history/#major-enhancements-v4-0-0)

Cache won't work in lower versions unless there is a custom implementation. I will release a fix. Thanks for reporting 👍🏻

**Comment by 10cheon00** [comment]
wow solved!
But github pages doesn't support jekyll 4  above versions. sad for that :(
Thank you for instantly responding my comment. Have a good day!

**Comment by gouravkhunger** [comment]
@10cheon00 GitHub Pages doesn't support custom plugins for any version of jekyll. Only specific [whitelisted plugins](https://pages.github.com/versions/) are available. If you want to use this plugin you need to either build site locally and host the `_site` folder. Or use a GitHub Action: [Example](https://github.com/gouravkhunger/jekyll-url-metadata/blob/main/.github/workflows/publish_site.yml).

@hanniabu For now the solution is to upgrade to Jekyll `>=4.0.0`. I will try to add logic for older jekyll versions in the meantime.

**Comment by 10cheon00** [comment]
Yes. After you gave a solution, I found that problem. Thank you for providing more information.
